# if commit_message != "Deploy Milind-Blaze/just_trying_stuff to github.com/Milind-Blaze/just_trying_stuff.git:gh-pages"


install:
- sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- sudo apt-get install latexmk
script:
- make
- make clean
env:
  global:
  - secure: dg2yePmY+NxfAMXSMQFcaukPFt4HONB8ysEkhtDZn8r2WBXHuP6PNcY4Dcgzlyxq+2KBoiZEMBOsT/6W3Zx7V02oUVRVqJPsbD4T654Wbc5yJfR3nUkEA3QBihvvrcXaKsnYjwn+hEthMoqt67tBbmL5yg1rFLRjMZY4JMgnqn1XC+woPAA15rtj3Z9en1fNLKpGDO4EELzfB80UzdbDxWrhcnsUxJfxWQ+s4cX4o+vNsPon6DWwwcjKBma3tuvygaimt93hgSqw61SilscGqUyUnOIiEnHv4xVYXVtus0W+aRGLtdeGLulxEafV9xa6SCQiPfAw2wq2pTdYUxlyVB4KXst2KBYOyPAZwvTiE+l25AM0LZ6ZQBOetXZg2AM5ettdEQ8QaAqtmMKWtlxxgNx+LbVKYKLuvc23CAXM6g+bBBvSiT+/qcvUv8jloPFNMpuvXNdD8s8XBhTmsxnCM0xdszSOeP4BUadfm+Syckk4IKVpyGk0hYkYD9gylrbEEdWjXNYVmdOSRmeiFFFo9YfDWyEH9MUBsht9ioxNTj0jfvNPXoh8WDVjHXXHT/rVlGX1ThRp6subgUgOGde3jE0pwtAug0wSPcYJBZjVeBUJQdyOC/WcBeLv+B6qdlgw7uZ8X1upVKroCNWw6jz57a7vWkQmSUHZo0JU43nUBIk=
  - secure: gNblCVS5tSprVcb1YIMHpDQ/c5z7WjePFx/VkiHFAH1C+aZjeUROcIOX4bpG+PBwSHQu1sy8+WII5bSOVt24LzjkJ4lXqBFezxYAQJ+w8AqDwQu4FW80knEWBXnHCOp8tPxFwtnWp16F0QcgPJKt0nmCdMONYfEuXcxl6oZvCvG3CL7T8IZYLnN4I7IM4R18ddrz4Ayn5L3ThowEU8VVec++NFKA88CrfK/ORElmYFXNzINVYieIR6+3qqcqjDg7p5BE2O2Vs9UooEa4i5SY9OvmN756c6RGoZo89gos90+ibTyrdVzSt78vVqmUb7BVfmDPM/IPE8yUEyB8eg+GV7FLIyr5Xv88VkkAf1AsPthjMPbo/W+I6h5ChXONQGlNpX4H2Z7UUBpLIkEpHIzhX4gt5PFHGGOwwOosERoaksXnRzG54QSUKOikiOAFZInWwCgahhqY/CH5/XkfGb2bxfdygmiT2p628VKY+xAO7Ss9R/2U2xpRjB4LjIDgtDBzYTyqB2onszNXB+quQjTRtiIPxEnJpVjk2QI4ucWtUzyL9Qas+TI2RkdUSSNqVOdC0eho8jjhpg1GkzNysJX692hbGKNbb4a+g3PMtZPWBLoqWI/Gc15Mk3E/E9x98KtJyI3UBTq8jPgr6KWgyTzHo7Im2LkHbDBm/Z6nwvPahzI=
  - secure: lgvClZoiuiTjCbEKxJkAySqhMpjNNrgEussUghNpXBqg9G5MEztn8pr75qQ44yxIdKn8oBlC2fkbGDJObyXYrDwWPqN9+vSE2BCq3atTikBgZnAD8pQ0artiFuwTyI90FQV3jWaUlxft1iSNHxS35zTeTpKh9MFyblAzGYjXHDy24gmq6UXr92FScgUm+Ih/RiaIVk1Wno41g/XFfRIZJRXRZKGSFLBUPR8xmvJh070+EtmwGu2duAyJFAGU5gFQYwNM2CjciGPoj12D2y+LaIByK27+rwaDhRwB/eKsqNWaB0Y/hkGNiGexQJn6MsouvFMtcO/Pg9i0/VYpecFNk6rLK+YYLnCK+g84/jumWYrviNJQx3kCCkfHzPs0JM6RbAxGxoRor0Rz4oavLe1C08TDNBzCIrDL2rfikH11VNHFP5EnvsSYC83AQGc9DP1g5/2vo+YqMDNpUYFT392m3bnnlKAiMWzsWj4WfNjNu6WbGJAbPfoZ8ks2DWqnto5c4XIBYiGUtGsp8gUPWHelSfdNL+CX+2y0tylD6V+EQd9NPiO+zF7oo5gMzoUYf9uJJqiBtbcFqWBCyPJrqrFWFE1kfiCqnTBKFyTUYv+uqUA746PojhdGhn2j4vjnNDYf3Pw+a1dUb6r1/UVjI1jI/FS7HTl/4VLiPvNEEwqDWPE=
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
  target_branch: master
