install:
- sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended #Required
- sudo apt-get install latexmk   #Required for latex make to work.
#Add more installation lines for all requirements of compiling your code


script: 

- make                      #Use make to call latexmk to compile your pdf
- make clean                #DO a cleanup of all auxiliary files.
#You can do other things as well if you like.

