install:
- sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- sudo apt-get install latexmk
script:
- cd proposals_and_reports
- make
- make clean
env:
  global:
  - secure: Y1zHN4aER79b4cwzwu4MOvQ+/9gXVGvpwhAb1admZYB4PA6fDgkZ2lKN9Sj+5DfECT2PCjSU7xIKFmVXjQaREyItfSEHWfT34+09f2j4qFES8KLR0Xlfn8UEDlq6zDEEjd308rkyIHOOxrKUPHYyj1IIch+OiVkFtzc6RW/C8oVMcq/pcVPkEn6TLMAMZFVFd4Yv6Rk1ZRDjAuSCMvb5ZdU32uvmg7nUREeqrKelbhfM9b++nvI3WHT0Tj88PmEjxlUank7U1BE+hbu1AjpxLO9nUbNDCAkNkrg20IRFhKfUtWpihDAf4DWK1mLCOn/ypM68FtK0AumBL6czufVnnA+CqIKYWwI8sw9BncalS6QyJgD4EMQHAOrPJ1PStSwFa8i7pw12u3a1knlyOvefOKzwXYu3NjEWxWB4mXzCGLy94JcpfFCOf2vo4D9H0q9E/2yuxsWqrzMM6ahXMPAMyRIqrOYJXJ0Hu8sBV1DIPk3zm/iqyTaTNNE9mqgvjDFD3bgIQ6esdiXhcV+oD5kPJpdhYtb407Ysh+YwIMEYf11BMiqHixacc8hUI0dedIfaM2gqAfMrwX6sKoQ/8C0hmT/DcT5S+bsol1u0FtBc6CMPad1QvpOUdnhhcssNchMuEAmPnHag++zp50ecf3r8/FapHuFwrddETZ7dj+HRBYI=
  - secure: i/1kRK6LO5IH6YPx9BLOO4iAhQy4rC93jETdBehrLJfCGypop/nwSaHtPZxksXiKe0PdLe1JOOTanjPW4a0ouAOF3tPMybtNWDUffSTOEeYrzTt1GzznmUj1PvkcIXr32z2ZYDTBGZKxLHU6Bxo1CLdAHclGWGWCwiMyxVFxrNS7LMt3ePvXOUGMgaP7xWMFQ6c8DYTznp9yg6+pPzoOa+xzhZuMcFu0uAk2sw02eioCx1IsmlTyrmkexNT6hBS8pNmypAUPlEZqY+WaSp2rN+JiVJPTG9Mtwj5vYC6JvwvLyvYvCtm4cRX53HSOIeN6qW3fuyDN7PKg8PYoTxcbJ66A5MjHhk3EOEHVOfAyf57FHZdjJrtv1k25NZrJG3CfqMn232Yzc9tA90FUgvefR0Qdi7wqRJtEEuTusJJXQZ/gzBRJADjjO84X1g8oqlhZ8xCmqF77IS3/fq+rqNtmotykUwXk3pxy0O2kzppqSBPza3ERizO737nkarJT9pl9hAsllcQ8LjW82kzzAuXX55GMdXiZBlZerC+wLDkjnc66Y1kpbb158hUlvwQ0eDLaCsImUX0EKjez7kCa49uzD1sdKUqX4i7PWHelUjmwddBzL8rSV9Oc0LY6Tj8dCYNLYMDHyLsJ5igZ818G6fn+KUTGZ2jhBcXwiDtEj2YFXho=
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
